name: Setup Project
description: Steps neccessary to setup the project
runs:
  using: "composite"
  steps:
    - name: Setup Node 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
      run: |
        npm install -g npm@9
        node -v && npm -v
        npm install
