extends: "./packages/eslint-config-terra/eslint.config.js"
overrides:
  - files:
    - "./packages/terra-functional-testing/tests/mocha/services/wdio-visual-regression-service/**/*.js"
    env:
      mocha: true
      node: true
    rules:
      prefer-arrow-callback: off
      func-names: off
      "space-before-function-paren": "off"
      import/no-extraneous-dependencies:
        - "error"
        - devDependencies: true
