version: '3.7'

services:
  hub:
   image: selenium/hub:${TERRA_SELENIUM_DOCKER_VERSION:-3.14.0-helium}
   ports:
     - "4444:4444"

  chrome:
    image: selenium/node-chrome:${TERRA_SELENIUM_DOCKER_VERSION:-3.14.0-helium}
    # Volume mounting is necessary to ensure the browser does not crash inside the docker container.
    # For more details see: 
    #  https://github.com/SeleniumHQ/docker-selenium#running-the-images
    #  https://bugs.chromium.org/p/chromium/issues/detail?id=519952
    #  https://bugzilla.mozilla.org/show_bug.cgi?id=1338771#c10
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  firefox:
    image: selenium/node-firefox:${TERRA_SELENIUM_DOCKER_VERSION:-3.141.59-titanium}
    # Volume mounting is necessary to ensure the browser does not crash inside the docker container.
    # For more details see: 
    #  https://github.com/SeleniumHQ/docker-selenium#running-the-images
    #  https://bugs.chromium.org/p/chromium/issues/detail?id=519952
    #  https://bugzilla.mozilla.org/show_bug.cgi?id=1338771#c10
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
