version: '3.4'

services:
  selenium_hub:
    image: selenium/hub:3.14.0-helium
    environment:
      GRID_THROW_ON_CAPABILITY_NOT_PRESENT: 'false'
      GRID_MAX_SESSION: 10
      GRID_BROWSER_TIMEOUT: 100000
      GRID_TIMEOUT: 90000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 150000
    ports:
      - '4444:4444'

  chrome:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      replicas: 1
    environment:
      HUB_HOST: selenium_hub
      HUB_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
      TZ: 'America/Chicago'
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  firefox:
    image: selenium/node-firefox:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      replicas: 1
    environment:
      HUB_HOST: selenium_hub
      HUB_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
      TZ: 'America/Chicago'
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
