---
#CI will run on all pushes and PRs to verify validity of the code
name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 1 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Clean Environment
        run: npm run clean
      - name: Install Dependencies
        run: npm install